# Generated by Django 4.2 on 2025-11-11 08:11

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_karma_points_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('chat', 'Chat'), ('call', 'Audio Call'), ('video', 'Video Call')], max_length=20)),
                ('duration', models.IntegerField(default=15)),
                ('user_query', models.TextField(blank=True)),
                ('birth_details', models.JSONField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('pandit_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('payment_status', models.CharField(default='paid', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user_rating', models.IntegerField(blank=True, null=True)),
                ('user_review', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Consultation Request',
                'verbose_name_plural': 'Consultation Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.CreateModel(
            name='PanditReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='users.consultationrequest')),
                ('pandit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pandit Review',
                'verbose_name_plural': 'Pandit Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PanditProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('specializations', models.JSONField(default=list)),
                ('languages', models.JSONField(default=list)),
                ('experience_years', models.IntegerField(default=0)),
                ('chat_rate', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=6)),
                ('call_rate', models.DecimalField(decimal_places=2, default=Decimal('200.00'), max_digits=6)),
                ('video_rate', models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=6)),
                ('availability_status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('offline', 'Offline')], default='offline', max_length=20)),
                ('working_hours', models.JSONField(default=dict)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('bank_ifsc', models.CharField(blank=True, max_length=20)),
                ('bank_account_holder', models.CharField(blank=True, max_length=100)),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_consultations', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pandit_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pandit Profile',
                'verbose_name_plural': 'Pandit Profiles',
            },
        ),
        migrations.CreateModel(
            name='PanditPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bank_account_number', models.CharField(max_length=50)),
                ('bank_ifsc', models.CharField(max_length=20)),
                ('bank_account_holder', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('admin_notes', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('pandit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pandit Payout',
                'verbose_name_plural': 'Pandit Payouts',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='pandit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pandit_consultations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_consultations', to=settings.AUTH_USER_MODEL),
        ),
    ]
