# Generated by Django 4.2 on 2025-11-11 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_consultationrequest_customuser_wallet_balance_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pandit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='users.panditprofile'),
        ),
        migrations.AlterField(
            model_name='chatthread',
            name='pandit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_threads', to='users.panditprofile'),
        ),
        migrations.DeleteModel(
            name='PanditProfile',
        ),
    ]
